import Head from "next/head";
import { Inter } from "@next/font/google";
import { Center, Text } from "@chakra-ui/react";

interface Props {
  title: string;
  children: React.ReactNode;
}

const inter = Inter({ subsets: ["latin"] });

const Layout = ({ title, children }: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center
          minH="100vh"
          flexDir={{ base: "column", md: "row" }}
          maxW="6xl"
          p={4}
          mx="auto"
          className={inter.className}
        >
          <Text
            fontSize={{ base: "2xl", md: "4xl" }}
            mb={{ base: 8, md: 0 }}
            textTransform="uppercase"
            letterSpacing="10px"
          >
            {title}
          </Text>
          {children}
        </Center>
      </main>
    </>
  );
};

export default Layout;
